pipeline {
    agent any 
    tools {
        maven 'M2_HOME'
        
    }
    stages {
        stage("checkout scm"){
            steps{
                checkout scm
            }
        }
        stage("sonacloud analysis"){
            steps{
                withSonarQubeEnv('sonarQube_server1'){
                    sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=HKRD4ever_geo-app'
                }                
            }            
        }
        stage("build"){
            steps{
                sh 'mvn clean; mvn validate; mvn compile; mvn install; mvn package; mvn test'
            }
        }
        stage("upload-artifact"){
            steps{
                sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd \
                -T target/bio*.jar \
                "http://ec2-3-95-32-32.compute-1.amazonaws.com:8081/artifactory/JFrogRepo/bio_${BUILD_TAG}"'
            }
        }
    }

}