pipeline {
    agent any 
    tools {
        maven 'M2_HOME'
        
    }
    stages {
        stage("checkout scm"){
            steps{
                checkout scm
            }
        }
        stage("sonacloud analysis"){
            steps{
                withSonarQubeEnv('sonarQube_server1')
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=HKRD4ever_geo-app'
            }
        }
    }

}