pipeline(
    agent any

    stages{
        stage("cmaven"){
            steps{
                sh 'mvn clean validate install test package'
                
            }
            
        }
    }
)